version: '3.6'

services:
  mysql:
      image: mysql:8.0.30
      ports:
        - "127.0.0.1:3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      volumes:
        - database:/var/lib/mysql
      networks:
        - default

volumes:
  database:
    driver: local